package GSMS.Recommendation;

import java.util.List;

/**
 * class to stand as component for recc AI
 */

public class RecommendationAI {

    public RecommendationAI() {

    } // end constructor

    /**
     * returns an exercise itinerary, given enrolled members'
     * profiles and the instructor-created itinerary
     * @param enrolledMemberProfiles
     * @param itinerary
     * @return
     */
    public String analyzeItinerary(List<String> enrolledMemberProfiles, String itinerary) {
        return null;
    } // end method

    /**
     * returns a workout generated by the Recommendation AI
     * for a given member associated with their profile with a
     * special focus on a given exercise type.
     * @param memberProfile
     * @param exerciseType
     * @return
     */
    public String generateWorkout(String memberProfile, String exerciseType) {
        return null;
    } // end method

} // end class