package GSMS.Recommendation;

import java.util.List;

/**
 * class to stand as component for recc AI
 */

public class RecommendationAI {

    public RecommendationAI() {

    } // end constructor

    /*
    getMemberProfile(memberID):
    sends a request to the Data Manager to retrieve a member’s profile
    given by their ID and retrieves it upon success.
    The profile information given here is limited to
    a member’s vitals, exercise routine in the gym,
    and medical conditions.
     */

    /**
     * returns an exercise itinerary, given enrolled members'
     * profiles and the instructor-created itinerary
     * @param enrolledMemberProfiles
     * @param itinerary
     * @return
     */
    public String analyzeItinerary(List<String> enrolledMemberProfiles, String itinerary) {
        return null;
    } // end method

    /**
     * returns a workout generated by the Recommendation AI
     * for a given member associated with their profile.
     * @param memberProfile
     * @return
     */
    public String generateWorkout(String memberProfile) {
        return null;
    } // end method

} // end class