package GSMS.Recommendation;

import java.util.List;

/**
 * class to stand as component for recc AI
 */

public class RecommendationAI {

    public RecommendationAI() {

    } // end constructor

    /**
     * returns an exercise itinerary, given enrolled members'
     * profiles and the instructor-created itinerary
     * @param enrolledMemberProfiles list of profiles of enrolled members in class
     * @param itinerary the itinerary to analyze
     * @return feedback on itinerary, warnings
     */
    public String analyzeItinerary(List<String> enrolledMemberProfiles, String itinerary) {
        return null;
    } // end method

    /**
     * returns a workout generated by the Recommendation AI
     * for a given member associated with their profile with a
     * special focus on a given exercise type.
     * @param memberProfile member profile to better customize the workout response
     * @param exerciseType what to focus on
     * @return a generated workout
     */
    public String generateWorkout(String memberProfile, String exerciseType) {
        // this is hard coded for the demo situation.
        /*
          PROMPT FOR CHATGPT: could you generate a workout recommendation for me? I've been
          feeling very low energy lately, pretty unenthused in my regular workout classes.
          But i still feel like i should do something at home today.
         */
        return """
                Low-Energy Reset Routine (20–30 minutes)
                
                1. Gentle warm-up (5–7 min)
                
                Keep it easy and fluid:
                
                + Neck rolls, shoulder circles
                + Cat–cow stretch
                + Slow bodyweight squats (just a few)
                + Light marching in place
                
                2. Light movement circuit (10–15 min)
                
                Do 2–3 rounds, no rush, no strict timing:
                
                + 8–10 Bodyweight Squat
                + 6–10 Push-Up (modify on knees or against a wall)
                + 10–12 Glute Bridge
                + 20–30 sec Plank (or shorter if needed)
                + 8–10 per side Bird Dog
                
                Take breaks whenever you want. The goal is just to move, not to exhaust yourself.
                
                3. Mood-boost finisher (optional, 5 min)
                
                Pick one:
                
                + Put on a song and just move/dance freely
                + Slow Yoga Flow sequence
                + A short walk outside if you feel up for it
                
                4. Wind down (5 min)
                
                + Forward fold, hamstring stretch
                + Deep breathing (in 4 sec, out 6 sec)
                + Lie down for a minute and just relax
                """;
    } // end method

} // end class