package GSMS.Recommendation;

import GSMS.Agents.AgentContainer;
import GSMS.Common.AgentId;
import GSMS.Common.AgentType;
import GSMS.Common.RecommendationType;
import GSMS.DataManagement.DataManager;
import GSMS.Notification.AlertLevel;
import GSMS.Notification.Notification;

/**
 * class to stand as component for recc dispatcher
 *
 * main functions:
 * + receive a request for (a) itinerary analysis or (b) workout generation
 * + send out (a) itnerary with feedback or (b) system generated workout
 */

public class RecommendationDispatcher {

    private RecommendationAI ai;

    public RecommendationDispatcher() {
        this.ai = new RecommendationAI();
    } // end constructor

    /**
     * entry point to receive an
     * analysis/recommendation request from a specific agent sender.
     * Optional data to include with the request may be given, such as an itinerary.
     * @param senderId id of the sending agent
     * @param requestType type of recc request: sys gen or analyze
     * @param requestData any additional info
     */
    public void receiveRequest(AgentId senderId, RecommendationType requestType, String requestData) {
        String recommendation = "No recc generated.";
        switch (requestType) {
            case SYSTEM_GENERATE:
                // generate with AI
                recommendation = ai.generateWorkout(DataManager.GetProfile(senderId, null), requestData);
                // keeping recommendation a string here, but would be a Workout(...)
                sendGeneratedWorkout(senderId, recommendation);
                break;

            case ANALYZE:
                // low priority, not in demo, so don't stress this for now.
                // analyze with AI
                // generate list of enrolled members with DataManager.GetProfile()
                // recommendation = ai.analyzeItinerary(list of enrolled, requestData)
                //
                // sendItinerary(senderId, new Itinerary(...))
                break;

            default:
                System.out.println("[RECC DISPATCH] A request type was received that is not recognized: " + requestType);
        } // end switch case
    } // end method

    /**
     * dispatches an exercise itinerary analyzed by the
     * Recommendation AI for a given instructor
     * associated with their ID.
     * @param instructorId instructor id
     * @param responseData the itineraru feedback
     */
    public void sendItinerary(AgentId instructorId, String responseData) {
        Notification information = new Notification(
                responseData, // Itinerary
                AlertLevel.INFORMATIONAL_MESSAGE,
                instructorId
        );
        if (instructorId.getType() == AgentType.INSTRUCTOR) {
            AgentContainer.InstructorApps.get(instructorId).sendInformation(information);
        } else {
            System.out.println("[RECC DISPATCH] Somehow a member or else used itinerary create: " + instructorId);
        } // end if
    } // end method

    /**
     * dispatches a generated workout as generated by the
     * Recommendation AI for a given member
     * associated with their ID
     * @param memberId member id
     * @param responseData the system generated workout
     */
    public void sendGeneratedWorkout(AgentId memberId, String responseData) {
        Notification information = new Notification(
                responseData, // Workout
                AlertLevel.INFORMATIONAL_MESSAGE,
                memberId
        );
        if (memberId.getType() == AgentType.MEMBER) {
            AgentContainer.MemberApps.get(memberId).sendInformation(information);
        } else {
            System.out.println("[RECC DISPATCH] Somehow an instructor or else used system generate: " + memberId);
        } // end if
    } // end method

} // end class