package GSMS.Recommendation;

/**
 * class to stand as component for recc dispatcher
 *
 * main functions:
 * + receive a request for (a) itinerary analysis or (b) workout generation
 * + send out (a) itnerary with feedback or (b) system generated workout
 */

public class RecommendationDispatcher {

    public RecommendationDispatcher() {

    } // end constructor

    /**
     * entry point to receive an
     * analysis/recommendation request from a specific agent sender.
     * Optional data to include with the request may be given, such as an itinerary.
     * @param senderId
     * @param requestType
     * @param requestData
     */
    public String receiveRequest(String senderId, String requestType, String requestData) {
        String result;
        switch (requestType) {
            case "make itinerary request":
                System.out.println("making itinerary for member " + senderId);
                result = "Lift 20 lbs dumbbells: 5 sets of 20 reps each hand\n";
                break;
            case "generate itinerary":
                System.out.println("generating itinerary based on preferences from " + senderId);
                result = "Lift 20 lbs dumbbells: 5 sets of 20 reps each hand\n";
                break;
            case "view schedule":
                System.out.println("Retrieving gym schedule for member " + senderId);
                result = "Nothing planned for today! Schedule now, ya slacker!\n";
                break;
            case "clear":
                result = "clear";
                break;
            default:
                result = "Invalid request!\n";
                System.out.println(result);
        }
        return result;
    } // end method

    /**
     * dispatches an exercise itinerary analyzed by the
     * Recommendation AI for a given instructor
     * associated with their ID.
     * @param instructorId
     * @param responseData
     */
    public String sendItinerary(String instructorId, String responseData) {
        String output;
        String data[] = responseData.split(" ");
        String member = data[0];
        String itinerary = data[1];
        output = instructorId + " has made itinerary for " + member + ":\n" + itinerary + "\n";
        return output;
    } // end method

    /**
     * dispatches a generated workout as generated by the
     * Recommendation AI for a given member
     * associated with their ID
     * @param memberId
     * @param responseData
     */
    public String sendGeneratedWorkout(String memberId, String responseData) {
        String output = memberId + " gets the following workout:\n" + responseData + "\n";
        return output;
    } // end method

} // end class